name: vulnix-action
description: vulnerability (CVE) scanner for Nix action
author: trev
branding:
  icon: anchor
  color: gray-dark

inputs:
  path:
    description: path to scan
    required: false
    default: "--system"
  score:
    description: minimum CVE score to report
    required: false
    default: "0"

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "Scanning path: ${{ inputs.path }} with minimum CVE score: ${{ inputs.score }}"

        set +e
        VULNERABILITIES=$(nix run github:nix-community/vulnix -- --json "${{ inputs.path }}")
        set -e

        RESULTS=$(echo "${VULNERABILITIES}" | jq -r '.[] | select(any(.cvssv3_basescore[]; . > ${{ inputs.score }})) | . as $item | .cvssv3_basescore | to_entries[] | select(.value > ${{ inputs.score }}) | "**Package:** \($item.name)  \n**CVE:** \(.key)  \n**Score:** \(.value)  \n**Description:** \($item.description[.key])\n\n---\n"')
        if [ -z "${RESULTS}" ]; then
          echo "No vulnerabilities with CVSSv3 score > ${{ inputs.score }} found."
          exit 0
        fi

        echo "## High Severity CVEs"
        echo ""
        echo "${RESULTS}"

        if [ -n "$GITHUB_STEP_SUMMARY" ]; then
          {
            echo "## <img src="https://brand.nixos.org/internals/nixos-logomark-default-gradient-none.svg" alt="NixOS" width="20"> High Severity CVEs"
            echo ""
            echo "${RESULTS}"
          } >> $GITHUB_STEP_SUMMARY
        fi

        exit 1

